// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psvystxipdleszajcgfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzdnlzdHhpcGRsZXN6YWpjZ2Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1Mzk1NjUsImV4cCI6MjA2MjExNTU2NX0.SwMOcN0b1D3JJXgwxaQz0qSNlqWrktofLE9L1q8flJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);